### ISSUE TITLE
non-polling invocation of watch

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-assistant#19]
It'd be handy to be able to invoke watch in a way so that it generates the output once, then exits, rather than polling in a loop. This allows the capturing of the nicely formatted output in a file in a reliable way.

I'm preparing a change to submit in a pull request that adds two optional flags to to watch:

```
    --refresh INT
```

which lets you set the poll time (in seconds), with a value < 0 meaning don't poll; and a "shortcut" version

```
    --once
```

as a synonym for `--refresh -1`

**Comment by illusional** [comment]
Hey @drtconway, thanks for the suggestion. There are two considerations here, the "refresh" interval would apply to clearing and updating the screen. I believe the default is 3 seconds currently. However, this wouldn't change how often the engine received updated information. Very happy to review a PR if you put one together.

In terms of polling information from the engine (Cromwell / CWLTool), it's up to the engine implementation to report info back to Janis, and each engine does this differently.

- CWLTool wrapper parses log info, so it will report info back immediately
- Cromwell wrapper polls the metadata at a set interval ([6 seconds](https://github.com/PMCC-BioinformaticsCore/janis-assistant/blob/master/janis_assistant/engines/cromwell/main.py#L409)).

For a technical note, the janis assistant has partial support for running and watching multiple workflows, that's sort of why you'll see an engineID and arrays of handlers in that class.

**Comment by illusional** [comment]
Closed by own PR #24.
